### ISSUE TITLE
[admin] [ Bug ] Unsaved changes window unnecessarily pops up on a new post

### ISSUE THREAD

**Issue by drorrose** [greenpress/greenpress#73] opened 2020-07-25 14:19 UTC
The window pops up even though I haven't visited the new post panel before. Not consistent.

**Comment by davidmeirlevy** [comment] 2021-07-22 06:46
closing this issue because it seems like it doesn't reproduce after the drafts-service was added.

**Closed by davidmeirlevy** 2021-07-22 06:46 UTC
