### ISSUE TITLE
[CLI] [BUG] greenpress start dev command

### ISSUE THREAD

**Issue by Man-RP** [greenpress/greenpress#93] opened 2021-06-17 17:48 UTC
node version 16.3.0
npm version 7.15.1
greenpress version 0.6.2

getting the following error after running greenpress start dev:

` Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run', 'local:dev' ]
}
`

**Comment by davidmeirlevy** [comment] 2021-09-25 17:57
Duplicate of #91 .

**Closed by davidmeirlevy** 2021-09-25 17:57 UTC
